### ISSUE TITLE
Extend options menu

### ISSUE THREAD

**Issue by michalove** [michalove/platformer#138]
Here we can collect what options should be available in the menu.
Currently we only have key-assignment.

We should add:
- toggle fullscreen
- volume of sound and music

Do we need more?

**Comment by Germanunkol** [comment]
I changed the look of the slider. Do you like it?

**Comment by michalove** [comment]
Yes, they are awesome.

**Comment by Germanunkol** [comment]
Update:

- [Done] Toggle Fullscreen
- [Done] Toggle Shaders
- [Not needed] Toggle Shadows
- [Not needed - set Volume to 0] Toggle background Music (on, off)
- [Done] Sound effect volume (0% to 100%)
- [Done] Music volume (0% to 100%)
- [Done] Keyboard assignment (submenu)
- [Done] Gamepad assignment (another submenu)
- [Done] Background quality

Some of these functions aren't assigned yet (music volume, parallax background settings) and some don't work perfectly yet (fullscreen switching is still slow), but menu-wise they're all done.

**Comment by michalove** [comment]
Cool. Thanks.

I might put all non-key-assignment options into one large menu. But otherwise, we are done here.

**Comment by Germanunkol** [comment]
Yes, I agree. The other menus are relatively small. I thought they'd be larger, but we don't really have that many options...
