### ISSUE TITLE
World map

### ISSUE THREAD

**Issue by michalove** [michalove/platformer#165]
The survey suggests these improvements:
- Use the 2d space to make a curved path. Not everything on a straight line.
- Make more beautiful images for the world.

It should also be possible to navigate to all other levels quickly. Especially those that are in other worlds. Maybe we should have a hierarchy. First select the world, then a new screen pops up showing the individual levels in the world.

**Comment by Germanunkol** [comment]
I think the new world map images look great, but I would consider moving the clouds to the end. The current levels towards the end feel a lot like they could be "cloudy", i.e. there's little ground and not many things to walk on...

**Comment by michalove** [comment]
Good advice. I will do that.

Also I will most probably add a 6th world, with only one level (the boss fight). This will most likely be a castle.
