### ISSUE TITLE
Obtaining new Bandanas

### ISSUE THREAD

**Issue by michalove** [michalove/platformer#216]
I finished the loading and saving of bandana color.

Also, I added a sort of splash-screen that gets displayed, when a bandana is collected in the campaign.
There, we can display info, about how to use the new ability. At the moment, there is only text, but I would like to add some images, too.

**Comment by michalove** [comment]
I improved the display of the GUI-Bandana icons and added some animations. This works well in the campaign.
Todo: Also implement it properly in the user levels.

**Comment by Germanunkol** [comment]
That looks really, really good!

**Comment by Germanunkol** [comment]
I really like all the new graphics, also those on the "New Bandana Panel" that pops up.
I was thinking though that it might be nice to see the bandana on the panel as well, larger, like a cloth in the new color either behind the title or, if that's annoying, hanging from the side of the panel itself?

Just an idea.

**Comment by michalove** [comment]
I tried your idea. Here are two mockups.
![upgrade_bg](https://cloud.githubusercontent.com/assets/3463790/7629344/0552d566-fa2c-11e4-85d9-58ccc4b7040d.png)
![upgrade_side](https://cloud.githubusercontent.com/assets/3463790/7629355/0f2a2a4e-fa2c-11e4-81d9-cbcf5f4b016f.png)

Generally, I like the first one more. The only thing is that the large yellow area looks a bit cheap. Maybe we need to add some shades there. What do you think? Or is that not what you wanted?

**Comment by Germanunkol** [comment]
Hm, I see what you mean and I agree.
Yes, shades would help, I think, maybe only around the edges (similar to 
how the Bamboo Box has a shadow on the right and top edges, maybe), and 
leading into the area a little bit from the sides, hinting at folds.
Another thing I'd change is: I would make the shapes less uneven. Right 
now it's the only thing on that image which is not rectangular. Maybe 
try something more along the lines of the green banner on this image:
http://www.misskatecuttables.com/uploads/shopping_cart/8378/large_banners-set.png
?

**Comment by michalove** [comment]
Here we go: First one is very straight
![upgrade_banner3](https://cloud.githubusercontent.com/assets/3463790/7631199/596d8994-fa3f-11e4-9d6a-0a51034f51b3.png)
the second one a bit curved
![upgrade_banner1](https://cloud.githubusercontent.com/assets/3463790/7631201/60e0f1fc-fa3f-11e4-9ebb-023444d9d134.png)
and the third one very curved and round
![upgrade_banner2](https://cloud.githubusercontent.com/assets/3463790/7631202/69e59a3c-fa3f-11e4-9650-ee8e53ba7a2c.png)

I think number 3 is the best one. What do you think?

**Comment by Germanunkol** [comment]
They're all very cool. Yes, use the third one! :)

Only thing: I'd put the shadow of that you currently have onto the left side instead. Otherwise it "clashes" with the direction of the light that the bamboobox uses...

**Comment by michalove** [comment]
Thanks for the note. I switched the shadow.
It was a good idea to add the bandana. I think it is very clear now, that a new bandana is added.
