### ISSUE TITLE
GUI: Currently available Bandanas

### ISSUE THREAD

**Issue by Germanunkol** [michalove/platformer#225]
We agreed on the following (correct me if I'm wrong):

GUI should show the Bandanas/Possible Actions
- in the pause menu
- for a short time after obtaining the bandana
- when starting or re-entering the campaign (as a reminder)

Where would you like the icons?
My current idea is to put them on the far right of the screen, starting at the bottom and building upwards, like a "stack".

**Comment by Germanunkol** [comment]
This does not work correctly yet. I'm still thinking about the best way to implement this, and I'm thinking I might change the behaviour to match the new setting in the editor.

Somehow, I still think the easiest thing would be the following:

The player has properties (which are booleans):
- hasRedBandana
- hasGreenBandana
- hasBlueBandana
...

We display these in the editor and simply let the user choose them. Additionally, the player can get bandanas by picking them up.

This would also make displaying the correct bandanas easier.
It would mean we have to set the bandanas manually on the campaign levels. But I can do that, it's not too much work with the new editor.

What do you think? Are you okay with this change? I think it makes the editor much more intuitive. Right now, when setting the player's bandana property, it is not clear what setting it to "red" means. Instead, we can have a property for each Bandana and simply give the player entity the bandana with the "highest ranking" color.

**Comment by michalove** [comment]
I recently changed the settings from a modular one to a linear one (that means red bandana automatically includes blue, green, yellow, white). But that was only a matter of communication. If we find a way to communicate to the player that he has the grappling hook, but cannot wall jump that this could make for some interesting levels.

So let's go back to the modular approach: Each ability is independent from the others. That means that in a user level the abilities need to be displayed on first start of the level.

In the campaign, though, the player should never lose abilities. Or what do you think? Is it fun to revisit old levels with new abilities?

**Comment by Germanunkol** [comment]
Okay, that sounds good! I think it's simply much easier to understand for the player.

We could even always display the abilities (but maybe make the images less intrusive, idea see below). I wouldn't mind - then it's very clear to the player at all times. When a bandana is blocked, then it could still be displayed in the corner, but crossed out.
Or do you want them to disappear?

![bandanasgui](https://cloud.githubusercontent.com/assets/1830593/7104683/5908b250-e0f2-11e4-9af4-2e42a40cd9c4.png)

**Comment by Germanunkol** [comment]
I think this is complete, your solution looks neat and works. Closing.
