### ISSUE TITLE
Show world map when going to next world, even when already in next world?

### ISSUE THREAD

**Issue by Germanunkol** [michalove/platformer#249]
Currently, when the player finishes the last level of a world, they get taken back to the world map, where they need to manually go to the next level. This makes sense when the new bridge gets created. But when it happens after the next world is already explored (i.e. this level has been finished before), then I feel it's very counter-intuitive.

It's due to Campaign:setLevel returning that "nextIsNew" is true, [here](https://github.com/michalove/platformer/blob/master/scripts/campaign.lua#L57).

Should we change this? Maybe don't show the world map unless the next level has never been played before?

**Comment by michalove** [comment]
You are right. I will change it so that the world map is only shown, when the level has never been played before.

**Comment by michalove** [comment]
Done
