### ISSUE TITLE
Error loading colors

### ISSUE THREAD

**Issue by Germanunkol** [michalove/platformer#250]
With the newest commit I get:

    Error: scripts/loading.lua:108: attempt to index global 'colors' (a nil value)
    stack traceback:
	scripts/loading.lua:108: in function 'draw'
	main.lua:95: in function 'draw'
	[string "boot.lua"]:438: in function <[string "boot.lua"]:399>
	[C]: in function 'xpcall'

**Comment by michalove** [comment]
Sorry. I forgot to upload the main.lua. Done now.

**Comment by Germanunkol** [comment]
Neat, that makes the menus look much nicer!
