### ISSUE TITLE
Show keys in upgrade-screen

### ISSUE THREAD

**Issue by michalove** [michalove/platformer#251]
When a new bandana is collected, I want to show the player which button to press to use it. Is there a quick and easy way of getting the image for the correct button?

**Comment by Germanunkol** [comment]
Yes. There's getAnimationForKey and getAnimationForPad.

There's an example of how to place a key image into the level as an object:
https://github.com/michalove/platformer/blob/master/scripts/objects/input.lua

Alternatively, there's [getImageForKey](https://github.com/michalove/platformer/blob/master/scripts/keys.lua#L243) and  [getImageForPad](https://github.com/michalove/platformer/blob/master/scripts/keys.lua#L272) if you need the on and off states of the button (which I don't think you need).

**Comment by michalove** [comment]
Phantastic. Done.
