### ISSUE TITLE
Rating Menu is missing in new Menu system

### ISSUE THREAD

**Issue by michalove** [michalove/platformer#256]
In the old scripts/menu.lua there was a function initRatingMenu. In the new menu, it does not seem to exist. Could you implement it? (The one with the skulls and stars).

**Comment by Germanunkol** [comment]
Sure!
It might take me a few weeks until I get around to it, though - I'm pretty busy atm.

**Comment by Germanunkol** [comment]
Done. Let me know if anything doesn't work as expected.
